Imds:
  ImdsSupport: v2.0
Image:
  Os: alinux2
  #  CustomAmi: ami-0f70b4ebcc9dbd7bd 
HeadNode:
  InstanceType: c6i.8xlarge
  Networking:
    SubnetId: subnet-0442a6e62ecc141f1
  Ssh:
    KeyName: pcluster-key
  LocalStorage:
    RootVolume:
      Size: 100
      DeleteOnTermination: true # that's your root and /home volume for users
  Iam:
    AdditionalIamPolicies: # grant ECR, SSM and S3 read access
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      - Policy: arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      - Policy: arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
Scheduling:
  Scheduler: slurm
  SlurmSettings:
    ScaledownIdletime: 60
  SlurmQueues:
    - Name: awsankur-g5-cluster
      CapacityType: ONDEMAND
      Networking:
        SubnetIds:
          - subnet-02517be9f404f6e12
        PlacementGroup:
          Enabled: true
      ComputeSettings:
        LocalStorage:
          EphemeralVolume:
            MountDir: /local_scratch # each instance has a local scratch on NVMe
          RootVolume:
            Size: 200
      # The capacity reservation section is recommended if you use instances
      # with a targeted ODCRs. You can also use a capacity resource group and
      # CapacityReservationResourceGroupArn if you want to regroup
      # multiple reservations
      #CapacityReservationTarget:
      #  CapacityReservationId: cr-06907041bc57e8549
      ComputeResources:
        - Name: awsankur-g5-cluster
          InstanceType: g5.8xlarge
          MinCount: 2 # if min = max then capacity is maintained and will
          MaxCount: 2 # not scale down
          Efa:
            Enabled: true
SharedStorage:
  - Name: SharedEBS
    StorageType: Ebs
    MountDir: /apps # Store your shared apps & scripts here
    EbsSettings:
      VolumeType: gp3
      Size: 200
      Throughput: 300
      Iops: 6000
Monitoring:
  DetailedMonitoring: true
  Logs:
    CloudWatch:
      Enabled: true # good for debug
  Dashboards:
    CloudWatch:
      Enabled: false # provide basic dashboards


